# Define the query templates with placeholders
query_templates = {
    "courses_offered": "What courses are being offered for the {semester} semester?",
    "professor_for_course": "Which professor is taking the course {course_name}?",
    "recommended_courses": "What courses do you recommend for the {semester} semester?",
    "related_courses": "What are the courses available related to {topic}?",
    "courses_on_day": "Can you suggest courses that take place on {day_of_week}?",
    "evening_classes": "Can you suggest classes only after {time}?",
    "online_courses": "Can you please suggest online courses to take?",
    "research_courses": "Can you suggest research or seminar-based courses?",
    "no_exam_courses": "Can you suggest courses without exams?",
    "easy_courses": "Can you suggest courses which are not too hectic and easy to get good grades?",
    "class_timings": "What are the class timings for the course {course_name}?",
    "prerequisite_courses": "Are there any prerequisite courses for {course_name}?",
    "course_reviews": "Has the course {course_name} been offered in the past? If so, could you summarize the reviews?",
    "courses_with_resources": "Suggest a course with good reading materials (resources from the professor).",
    "courses_by_professor": "What courses are being offered by Professor {professor_name}?"
}

seed_query_list =[ "What courses are being offered for the {semester} semester?",
 "Which professor is taking the course {course_name}?",
 "What courses do you recommend for the {semester} semester?",
 "What are the courses available related to {topic}?",
 "Can you suggest courses that take place on {day_of_week}?",
 "Can you suggest classes only after {time}?",
 "Can you please suggest online courses to take?",
 "Can you suggest research or seminar-based courses?",
 "Can you suggest courses without exams?",
 "Can you suggest courses which are not too hectic and easy to get good grades?",
 "What are the class timings for the course {course_name}?",
 "Are there any prerequisite courses for {course_name}?",
 "Has the course {course_name} been offered in the past? If so, could you summarize the reviews?",
 "Suggest a course with good reading materials (resources from the professor).",
 "What courses are being offered by Professor {professor_name}?"]

topics = [
    'Fundamentals of Computer Science',
    'Algorithms and Data Structures',
    'Object-Oriented Design',
    'Software Development',
    'Theory of Computation',
    'Data Science',
    'Artificial Intelligence',
    'Computer Systems',
    'Networks and Distributed Systems',
    'Game Programming',
    'Complex Network Analysis',
    'Health Informatics',
    'Robotics',
    'Statistical Methods',
    'Database Management Systems',
    'Computer Graphics',
    'Web Development',
    'Mobile Application Development',
    'Machine Learning',
    'Natural Language Processing',
    'Cybersecurity',
    'Information Visualization',
    'Programming Languages',
    'Compilers',
    'Software Engineering',
    'Operating Systems',
    'Computer Architecture',
    'Human-Computer Interaction'
]