name: Trigger Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'data_pipeline/**'
      - 'model_training/**'

env:
  GCP_COMPOSER_NAME: ${{ vars.GCP_COMPOSER_NAME }}
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        echo "Running tests..."
        pytest
      env:
        PYTHONPATH: ${{github.workspace}}

  trigger-banner-dag:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      dag_completed: ${{ steps.wait-for-dag.outputs.dag_completed }}
      dag_skipped: ${{ steps.check-skip-condition.outputs.dag_skipped }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if files have been changed in data_pipeline
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: data_pipeline/**
          files_ignore: data_pipeline/dags/tests/**

      - name: Skip DAG Trigger
        id: check-skip-condition
        if: steps.changed-files-specific.outputs.any_changed != 'true'
        run: |
            echo "No changes in data_pipeline detected. Skipping DAG trigger."
            echo "dag_skipped=true" >> $GITHUB_OUTPUT
            exit 0

      - name: Setup Auth
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: coursecompass

      - name: Trigger DAG
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          gcloud composer environments run "$GCP_COMPOSER_NAME" \
              --location us-east1 \
              dags trigger -- banner_dag_pipeline
              echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
  
  trigger-model-training-dag:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if files have been changed in model_training
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: model_training/**
          files_ignore: model_training/dags/tests/**

      - name: Skip DAG Trigger Check
        if: steps.changed-files-specific.outputs.any_changed != 'true'
        run: |
            echo "No changes in model_training detected. Skipping DAG trigger."
            exit 0

      - name: Skip DAG Trigger Check
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
            echo "Changes in model_training detected. Triggering DAG."
            exit 0

      - name: Setup Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: coursecompass

      - name: Trigger DAG
        run: |
          gcloud composer environments run "$GCP_COMPOSER_NAME" \
          --location us-east1 \
          dags trigger -- banner_dag_pipeline
          echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
