name: Upload to GCS

on:
  push:
    branches:
      - workflow-testing

jobs:
  upload_to_gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        project_id: coursecompass
        service_acount: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        

    - name: Upload files to GCS
      run: |
        gsutil cp -r ./data_pipeline gs://us-central1-data-pipeline-e0d20662-bucket/
